The problem occurs because you set the variable as INPUT_STORE in your workflow and extract as INPUT_MYINPUT in your python script. Use the same variable and it should work.

I made it work like this:

Workflow file:

name: Test Python Input

on:
   workflow_dispatch:
     inputs:
       myInput:
         description: 'User Input:'
         required: true
         default: 

jobs:
  run-python-test:
   runs-on: ubuntu-latest
    steps:
  
  - name: Checkout
    uses: actions/checkout@v2.3.4
  
  - name: Setup Python
    uses: actions/setup-python@v2.2.2
    with:
      python-version: ["3.9", "3.10", "3.11"]
  
  - name: Execute Test Script
    run: |
      echo "Store: ${{ github.event.inputs.myInput }}"
      INPUT_STORE=${{ github.event.inputs.myInput }} python3 test.py
